### ISSUE TITLE
請問pytorch要用哪個版本?

### ISSUE THREAD

**Issue by a240888** [Bacon9629/racecar_gym#2]
PPT裡面說明用Pytorch 2.0.1，但是yml檔裡面是Pytorch 2.0.0，同樣問題還有發生在matplotlib上，請問要以哪邊為主?
(補充:有同學反應Pytorch 2.0.1會有Numpy版本不兼容的問題)

**Comment by a240888** [comment]
補充:有同學反應Pytorch 2.0.1會有Numpy版本不兼容的問題

**Comment by Zhong-Zi-Zeng** [comment]
同學你好，這邊統一使用Pytorch 2.0.0、matplotlib 3.8.1，依yaml檔裡的為主 (講義投影片忘記更新了)
