### ISSUE TITLE
影像處理的套件

### ISSUE THREAD

**Issue by wl03080321** [Bacon9629/racecar_gym#3]
您好，我想請問由於要處理影像的資訊，會在agent裡的程式碼import Pillow影像處理的套件，這會不允許嗎? 謝謝

**Comment by Zhong-Zi-Zeng** [comment]
同學你好，這部分是ok的，不過還是建議使用cv2取代PIL

**Comment by wl03080321** [comment]
謝謝助教回答，還有想請教State['wrong_way']這個布林值狀態我很困惑，他是在怎麼樣的情況下會變成True，因為我測試有時候車子是直線走但是往返的方向跑卻是False，但有時會是True，以及obs_preprocess函式的註解中有包含Time的變數，但在ppt上是屬於state的資訊，所以這個time是可以當作observation嗎?

**Comment by Zhong-Zi-Zeng** [comment]
同學你好，針對第一點的問題，我們判斷他地圖內部有設置幾個檢查點，所以應該是通過那個來觸發的。而第二個問題time是誤打上去的😂，所以不能使用time來當作observation

**Comment by wl03080321** [comment]
了解，我還有個小問題，我想請教ppt的模型範例中大約練了多少個epoch才有明顯的成效表現，每次改code重練都不見的有效，不確定是我設計的問題，還是練的epoch不夠久，所以想設定一個epoch停損點，謝謝助教回覆!

**Comment by Bacon9629** [comment]
同學你好
如果是PPO的話，約10個Epoch就可以看到有train起來的跡象，這時候就值得投資時間在這次上面。如果跑了兩三小時後reward都一直沒上去的話就可以考慮停掉這次重新設計了。
如果是DQN的話，就只能聽天由命了......，Obeservation space和Action space的大小會與DQN的收斂時間呈正相關，或許可以設定一個比較小的Obeservation space和Action space，然後放個30~50 epoch，如果沒什麼起色也可以考慮停掉了。

另外在`austria`這個賽道，第二個彎是難度非常高的點，通常model都會卡在這邊一陣子，我是建議可以看看車子有沒有嘗試轉向或煞車，如果車子在第二個彎有嘗試轉向或煞車、而不是直直撞向牆壁，那這次的training就有可能會成功。

以上是我的看法，僅供參考

**Comment by wl03080321** [comment]
了解了，謝謝助教回覆，我還有個疑問對於Observation的lidar陣列的值，它是顯示360度當中可能的物體距離嗎，還是不只是360度?

**Comment by Bacon9629** [comment]
lidar掃描範圍大約是180度左右

**Comment by wl03080321** [comment]
學長好，我想請問最終比賽用的模型會是10/12號繳交作業的模型嗎。

**Comment by Zhong-Zi-Zeng** [comment]
是的沒有錯
