### ISSUE TITLE
[公告] 測試環境指令修正

### ISSUE THREAD

**Issue by Bacon9629** [Bacon9629/racecar_gym#6]
前次版本的README有提到如果要測試環境，可透過執行`validation_script.py`來測試，但如果在沒有training weight的情況下執行`validation_script.py`的話會導致程式無法執行。

因此新增測試文件`check_env_script.py`，若是需要測試環境的話請改為執行`python check_env_script.py`來進行測試。

---
以上修正皆已更新至commit ID: `10456498cb1a504cf6125acb6b850d6eb5c88b33`，可透過指令`git pull`或重新下載專案取得最新程式碼

**Comment by Khakit20** [comment]
助教好 在尚未新增check_env_script.py時 我的程式是可以進行完整訓練以及順利驗證的 但我再將新的pull下來後發現我的程式突然就不能執行了 他一直報錯 請問有這個檔案我沒有注意到嗎?
![image](https://github.com/user-attachments/assets/40b8de75-b37a-449f-a7c7-c13edc449188)

**Comment by Bacon9629** [comment]
同學你好
你提到的錯誤是因為在check_env_script.py裡面所使用的地圖是錯誤的，這部份是我打錯
感謝你的回報，我已經修正，麻煩再pull一次！
