### ISSUE TITLE
訓練結果

### ISSUE THREAD

**Issue by retyuuu** [Bacon9629/racecar_gym#8]
助教好，想詢問在訓練過程中，我第一次訓練(100個epoch)的結果很好，但在第二次訓練(100個epoch)時機器彷彿沒有訓練過，表現很差，是因為要改動甚麼代碼讓他讀取到上次訓練的參數嗎

**Comment by retyuuu** [comment]
另外是不是更改reward fuction的話會建議從新訓練參數檔

**Comment by Bacon9629** [comment]
這部分建議參考 [dqn_agent.py](https://github.com/Bacon9629/racecar_gym/blob/master/agent/DQN/dqn_agent.py)第71行與[ppo_agent.py](https://github.com/Bacon9629/racecar_gym/blob/master/agent/PPO/ppo_agent.py)第61行，這邊寫著load model的邏輯
簡單來說就是如果是在training時，預設會重新訓練一個model並且把weight檔覆蓋，因此可以依照自己的需求將training完的weight檔備份、或是讓它被覆蓋
當然這部分的code可以隨自己的意進行更改，只要確保你的code可以在我們的電腦上透過validation_script.py正常loading model就OK

關於第二個問題，確實有一個training方式是類似漸進式學習的方式，可以先設定一個初始reward function，訓練到中期時依照狀況微調reward function內容
但若你是將reward function大修改的話建議重新訓練一個會比較好
